// Package tiltgen generates a Tiltfile from devstack manifests, so a workspace's
// configuration lives entirely in devstack.workspace.yaml + devstack.service.yaml
// and the Tiltfile becomes a build artifact that is never hand-edited.
package tiltgen

import (
	"fmt"
	"sort"
	"strconv"
	"strings"

	"github.com/socialviolation/devstack/internal/config"
)

// Options carries generation inputs the manifests don't hold themselves.
type Options struct {
	// ManagedEnv holds devstack-computed values, keyed by service name. These are
	// facts about what is actually running, so they sit at the highest precedence
	// and override every manifest and .envrc layer.
	ManagedEnv map[string]map[string]string

	// Book, when non-nil, is used verbatim as the port book instead of
	// BuildPortBook(rw). Stack generation supplies the overlay-first merged book so
	// references resolve to allocated ports; callers that leave it nil get the
	// manifest-derived book unchanged.
	Book config.PortBook

	// StackEnv names the env applied at the stack scope. Base generation leaves it
	// empty; stack generation sets it from the stack's record so the stack scope
	// layers into the env ladder above the manifests' static values.
	StackEnv string
}

const header = `# GENERATED BY devstack — DO NOT EDIT.
# Source of truth: devstack.workspace.yaml + each service's devstack.service.yaml.
# Regenerate with: devstack workspace up  (or: devstack workspace generate)
`

// namespaceDelim separates a service name from its stack namespace in a Tilt
// resource name (e.g. "navexa-api:perf"). Tilt accepts ":" in resource names, so
// a stack's resources coexist with base's without collision.
const namespaceDelim = ":"

// StackGen is one feature stack contributed to a combined Tiltfile: its resolved
// workspace (worktree checkouts), the generation options (overlay-first book,
// base OTEL) built by stack.GenerateOptions, and the namespace its resources are
// filed under (the stack's short name).
type StackGen struct {
	Workspace *config.ResolvedWorkspace
	Options   Options
	Namespace string
}

// WorkspaceGen is one workspace folded into the host Tiltfile: its base
// resolved workspace + options, plus its active stacks.
type WorkspaceGen struct {
	Name     string
	Base     *config.ResolvedWorkspace
	BaseOpts Options
	Stacks   []StackGen
}

// GenerateHost renders one Tiltfile composing every workspace's base services
// plus each active stack's overlay services, all as distinct resources. Every
// resource name is prefixed with its workspace name (<ws>:<svc>, or
// <ws>:<svc>:<stack> for a stack), so services of the same name in different
// workspaces never collide, resource_deps rewire within their own workspace and
// stack, and each resource carries its workspace name as a Tilt label.
// Workspaces are rendered in the given order.
func GenerateHost(workspaces []WorkspaceGen) (string, error) {
	if err := ValidateFreePorts(workspaces); err != nil {
		return "", err
	}

	var b strings.Builder
	b.WriteString(header)

	for _, w := range workspaces {
		if w.Base == nil || w.Base.Manifest == nil {
			return "", fmt.Errorf("workspace %q: nil resolved workspace", w.Name)
		}
		if err := renderWorkspace(&b, w.Base, w.BaseOpts, w.Name, ""); err != nil {
			return "", fmt.Errorf("workspace %q: %w", w.Name, err)
		}
		for _, s := range w.Stacks {
			if s.Workspace == nil || s.Workspace.Manifest == nil {
				return "", fmt.Errorf("workspace %q stack %q: nil resolved workspace", w.Name, s.Namespace)
			}
			if err := renderWorkspace(&b, s.Workspace, s.Options, w.Name, s.Namespace); err != nil {
				return "", fmt.Errorf("workspace %q stack %q: %w", w.Name, s.Namespace, err)
			}
		}
	}

	return b.String(), nil
}

// renderWorkspace writes every service block for one workspace into b. A non-empty
// namespace makes the block a stack overlay: resource names and their
// resource_deps are suffixed :<namespace> and the namespace is added as a label.
// A non-empty prefix (host mode) prepends <prefix>: to every resource name and
// resource_dep and adds the prefix as a label.
func renderWorkspace(b *strings.Builder, rw *config.ResolvedWorkspace, opts Options, prefix, namespace string) error {
	groupsOf := map[string][]string{}
	for group, members := range rw.Manifest.Groups {
		for _, m := range members {
			groupsOf[m] = append(groupsOf[m], group)
		}
	}
	for _, gs := range groupsOf {
		sort.Strings(gs)
	}

	names := make([]string, 0, len(rw.Services))
	for name := range rw.Services {
		names = append(names, name)
	}
	sort.Strings(names)

	book := opts.Book
	if book == nil {
		book = config.BuildPortBook(rw)
	}

	for _, name := range names {
		svc := rw.Services[name]
		if svc.Manifest == nil {
			return fmt.Errorf("service %q has no manifest (legacy .devstack.json cannot be generated from)", name)
		}
		block, err := renderService(svc, rw.Manifest, groupsOf[name], opts, book, prefix, namespace)
		if err != nil {
			return fmt.Errorf("service %q: %w", name, err)
		}
		b.WriteString(block)
	}
	return nil
}

// hostName joins the non-empty of [prefix, name, suffix] with namespaceDelim.
// With an empty prefix it equals the old suffix-only namespacing (name, or
// name:suffix); host mode supplies the workspace prefix to yield prefix:name or
// prefix:name:suffix.
func hostName(prefix, name, suffix string) string {
	parts := make([]string, 0, 3)
	if prefix != "" {
		parts = append(parts, prefix)
	}
	parts = append(parts, name)
	if suffix != "" {
		parts = append(parts, suffix)
	}
	return strings.Join(parts, namespaceDelim)
}

func renderService(svc config.ResolvedService, ws *config.WorkspaceManifest, groups []string, opts Options, book config.PortBook, prefix, namespace string) (string, error) {
	m := svc.Manifest
	if m.Runtime.Run.Command == "" {
		return "", fmt.Errorf("runtime.run.command is required")
	}

	runCmd, err := config.ResolveRefs(m.Runtime.Run.Command, svc.Name, book)
	if err != nil {
		return "", err
	}

	serveDir := svc.EnvDir()

	var b strings.Builder
	fmt.Fprintf(&b, "\n# %s\n", hostName(prefix, svc.Name, namespace))
	b.WriteString("local_resource(\n")
	fmt.Fprintf(&b, "    %s,\n", starStr(hostName(prefix, svc.Name, namespace)))

	prep, err := prepCommand(m, svc.Name, book)
	if err != nil {
		return "", err
	}
	if prep != "" {
		fmt.Fprintf(&b, "    cmd=%s,\n", starStr(prep))
	}

	fmt.Fprintf(&b, "    serve_cmd=%s,\n", starStr(runCmd))
	fmt.Fprintf(&b, "    serve_dir=%s,\n", starStr(serveDir))

	layers, err := config.EnvLadder(serveDir, ws, m, opts.StackEnv, opts.ManagedEnv[svc.Name])
	if err != nil {
		return "", err
	}
	if err := ResolveLayerRefs(layers, svc.Name, book); err != nil {
		return "", err
	}
	if err := checkRequiredEnv(layers, m.Env.Required, svc.Name); err != nil {
		return "", err
	}
	if env := config.MergeEnvLadder(layers); len(env) > 0 {
		b.WriteString("    serve_env={\n")
		for _, k := range sortedKeys(env) {
			fmt.Fprintf(&b, "        %s: %s,\n", starStr(k), starStr(env[k]))
		}
		b.WriteString("    },\n")
	}

	fmt.Fprintf(&b, "    trigger_mode=%s,\n", triggerMode(m.Runtime.TriggerMode))
	fmt.Fprintf(&b, "    auto_init=%s,\n", pyBool(m.Runtime.AutoStart))

	labels := append([]string{}, groups...)
	if namespace != "" {
		labels = append(labels, namespace)
	}
	if prefix != "" {
		labels = append(labels, prefix)
	}
	if len(labels) > 0 {
		fmt.Fprintf(&b, "    labels=[%s],\n", starList(labels))
	}
	if deps := ws.ResourceDeps(svc.Name); len(deps) > 0 {
		nsDeps := make([]string, len(deps))
		for i, d := range deps {
			nsDeps[i] = hostName(prefix, d, namespace)
		}
		fmt.Fprintf(&b, "    resource_deps=[%s],\n", starList(nsDeps))
	}
	if len(m.Runtime.Watch) > 0 {
		fmt.Fprintf(&b, "    deps=[%s],\n", starList(m.Runtime.Watch))
	}
	healthcheck := m.Runtime.Healthcheck
	if healthcheck.Command != "" {
		resolved, err := config.ResolveRefs(healthcheck.Command, svc.Name, book)
		if err != nil {
			return "", err
		}
		healthcheck.Command = resolved
	}
	if probe := renderProbe(healthcheck); probe != "" {
		fmt.Fprintf(&b, "    readiness_probe=%s,\n", probe)
	}
	links, err := buildLinks(svc.Name, m, book)
	if err != nil {
		return "", err
	}
	if len(links) > 0 {
		parts := make([]string, 0, len(links))
		for _, l := range links {
			parts = append(parts, fmt.Sprintf("link(%s, %s)", starStr(l.url), starStr(l.label)))
		}
		fmt.Fprintf(&b, "    links=[%s],\n", strings.Join(parts, ", "))
	}

	b.WriteString(")\n")
	return b.String(), nil
}

// ResolveLayerRefs resolves ${service.field} references in the workspace/service
// env.values layers against the port book, in place — the same resolution the
// generated serve_env receives, so callers can preview it.
func ResolveLayerRefs(layers []config.EnvLayer, self string, book config.PortBook) error {
	for i := range layers {
		if layers[i].Rung != config.RungWorkspaceValues && layers[i].Rung != config.RungServiceValues {
			continue
		}
		resolved := make(map[string]string, len(layers[i].Values))
		for k, v := range layers[i].Values {
			rv, err := config.ResolveRefs(v, self, book)
			if err != nil {
				return err
			}
			resolved[k] = rv
		}
		layers[i].Values = resolved
	}
	return nil
}

func checkRequiredEnv(layers []config.EnvLayer, required []string, service string) error {
	var missing []string
	for _, key := range required {
		found := false
		for _, l := range layers {
			if v, ok := l.Values[key]; ok && strings.TrimSpace(v) != "" {
				found = true
				break
			}
		}
		if !found {
			missing = append(missing, key)
		}
	}
	if len(missing) == 0 {
		return nil
	}
	sort.Strings(missing)
	return fmt.Errorf("service %q missing required env: %s", service, strings.Join(missing, ", "))
}

type serviceLink struct {
	url   string
	label string
}

// buildLinks merges a service's links: derived one per ports: entry, plus any
// explicit links: (references resolved). Explicit links keep their manifest
// order, and a derived link is dropped when an explicit link already covers its
// URL, so an explicit link for a port replaces the bare derived default.
func buildLinks(self string, m *config.ServiceManifest, book config.PortBook) ([]serviceLink, error) {
	var out []serviceLink
	seen := map[string]bool{}

	for _, l := range m.Links {
		url, err := config.ResolveRefs(l.URL, self, book)
		if err != nil {
			return nil, err
		}
		label := l.Label
		if label == "" {
			label = self
		}
		out = append(out, serviceLink{url: url, label: label})
		seen[url] = true
	}

	keys := make([]string, 0, len(m.Ports))
	for k := range m.Ports {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, key := range keys {
		port := m.Ports[key]
		if bp, ok := book[self][key]; ok {
			port = bp
		}
		url := fmt.Sprintf("http://%s:%d", book.Host(self), port)
		if seen[url] {
			continue
		}
		out = append(out, serviceLink{url: url, label: key})
		seen[url] = true
	}

	return out, nil
}

func renderProbe(h config.ServiceHealthcheck) string {
	period := h.PeriodSecs
	if period == 0 {
		period = 5
	}
	fails := h.FailureThreshold
	if fails == 0 {
		fails = 10
	}
	switch h.Type {
	case "exec":
		if h.Command == "" {
			return ""
		}
		return fmt.Sprintf("probe(exec=exec_action([%s, %s, %s]), period_secs=%d, failure_threshold=%d)",
			starStr("bash"), starStr("-c"), starStr(h.Command), period, fails)
	case "http":
		if h.Port == 0 {
			return ""
		}
		path := h.Path
		if path == "" {
			path = "/"
		}
		return fmt.Sprintf("probe(http_get=http_get_action(port=%d, path=%s), period_secs=%d, failure_threshold=%d)",
			h.Port, starStr(path), period, fails)
	default:
		return ""
	}
}

func triggerMode(mode string) string {
	if strings.EqualFold(mode, "auto") {
		return "TRIGGER_MODE_AUTO"
	}
	return "TRIGGER_MODE_MANUAL"
}

func pyBool(b bool) string {
	if b {
		return "True"
	}
	return "False"
}

// starStr renders a Go string as a Starlark/Python double-quoted literal.
func starStr(s string) string {
	return fmt.Sprintf("%q", s)
}

func starList(items []string) string {
	parts := make([]string, len(items))
	for i, s := range items {
		parts[i] = starStr(s)
	}
	return strings.Join(parts, ", ")
}

func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// prepCommand builds the one-shot command Tilt runs before starting a service:
// devstack's own port reclaim (when the service asks for it) followed by the
// service's own prep.
//
// The reclaim is generated from the ports THIS instance resolved to, never from
// a literal in the manifest. A hand-written `fuser -k 63290/tcp` is copied
// verbatim into every stack's worktree, where it names base's port and kills
// base each time the stack starts. Deriving it here means a stack can only ever
// free what it was allocated.
func prepCommand(m *config.ServiceManifest, service string, book config.PortBook) (string, error) {
	var parts []string

	if m.Runtime.Prep.FreePorts.Enabled() {
		targets, err := m.Runtime.Prep.FreePorts.Resolve(service, book[service])
		if err != nil {
			return "", err
		}
		if len(targets) > 0 {
			args := make([]string, 0, len(targets))
			for _, p := range targets {
				args = append(args, strconv.Itoa(p))
			}
			parts = append(parts, "devstack ports free --quiet "+strings.Join(args, " "))
		}
	}

	if cmd := strings.TrimSpace(m.Runtime.Prep.Command); cmd != "" {
		resolved, err := config.ResolveRefs(cmd, service, book)
		if err != nil {
			return "", err
		}
		parts = append(parts, resolved)
	}

	return strings.Join(parts, " && "), nil
}
