// Package tiltgen generates a Tiltfile from devstack manifests, so a workspace's
// configuration lives entirely in devstack.workspace.yaml + devstack.service.yaml
// and the Tiltfile becomes a build artifact that is never hand-edited.
package tiltgen

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"github.com/socialviolation/devstack/internal/config"
)

// Options carries generation inputs the manifests don't hold themselves.
type Options struct {
	// ManagedEnv are devstack-injected env defaults (e.g. the OTEL endpoint)
	// applied to every service at the lowest precedence. Workspace- and
	// service-level env override these.
	ManagedEnv map[string]string
}

const header = `# GENERATED BY devstack — DO NOT EDIT.
# Source of truth: devstack.workspace.yaml + each service's devstack.service.yaml.
# Regenerate with: devstack up  (or: devstack generate)
`

// Generate renders a Tiltfile for the resolved workspace.
func Generate(rw *config.ResolvedWorkspace, opts Options) (string, error) {
	if rw == nil || rw.Manifest == nil {
		return "", fmt.Errorf("nil resolved workspace")
	}

	// service name -> sorted groups it belongs to (drives Tilt UI labels)
	groupsOf := map[string][]string{}
	for group, members := range rw.Manifest.Groups {
		for _, m := range members {
			groupsOf[m] = append(groupsOf[m], group)
		}
	}
	for _, gs := range groupsOf {
		sort.Strings(gs)
	}

	names := make([]string, 0, len(rw.Services))
	for name := range rw.Services {
		names = append(names, name)
	}
	sort.Strings(names)

	var b strings.Builder
	b.WriteString(header)

	for _, name := range names {
		svc := rw.Services[name]
		if svc.Manifest == nil {
			return "", fmt.Errorf("service %q has no manifest (legacy .devstack.json cannot be generated from)", name)
		}
		block, err := renderService(svc, rw.Manifest, groupsOf[name], opts)
		if err != nil {
			return "", fmt.Errorf("service %q: %w", name, err)
		}
		b.WriteString(block)
	}

	return b.String(), nil
}

func renderService(svc config.ResolvedService, ws *config.WorkspaceManifest, groups []string, opts Options) (string, error) {
	m := svc.Manifest
	if m.Runtime.Run.Command == "" {
		return "", fmt.Errorf("runtime.run.command is required")
	}

	serveDir := svc.RepoPath
	if m.Runtime.WorkDir != "" && m.Runtime.WorkDir != "." {
		serveDir = filepath.Join(svc.RepoPath, m.Runtime.WorkDir)
	}

	var b strings.Builder
	fmt.Fprintf(&b, "\n# %s\n", svc.Name)
	b.WriteString("local_resource(\n")
	fmt.Fprintf(&b, "    %s,\n", starStr(svc.Name))

	if prep := m.Runtime.Prep.Command; prep != "" {
		fmt.Fprintf(&b, "    cmd=%s,\n", starStr(prep))
	}

	fmt.Fprintf(&b, "    serve_cmd=%s,\n", starStr(serveCmd(m, ws)))
	fmt.Fprintf(&b, "    serve_dir=%s,\n", starStr(serveDir))

	if env := mergedEnv(opts.ManagedEnv, ws.Env.Values, m.Env.Values); len(env) > 0 {
		b.WriteString("    serve_env={\n")
		for _, k := range sortedKeys(env) {
			fmt.Fprintf(&b, "        %s: %s,\n", starStr(k), starStr(env[k]))
		}
		b.WriteString("    },\n")
	}

	fmt.Fprintf(&b, "    trigger_mode=%s,\n", triggerMode(m.Runtime.TriggerMode))
	fmt.Fprintf(&b, "    auto_init=%s,\n", pyBool(m.Runtime.AutoStart))

	if len(groups) > 0 {
		fmt.Fprintf(&b, "    labels=[%s],\n", starList(groups))
	}
	if deps := ws.Dependencies[svc.Name]; len(deps) > 0 {
		sorted := append([]string(nil), deps...)
		sort.Strings(sorted)
		fmt.Fprintf(&b, "    resource_deps=[%s],\n", starList(sorted))
	}
	if len(m.Runtime.Watch) > 0 {
		fmt.Fprintf(&b, "    deps=[%s],\n", starList(m.Runtime.Watch))
	}
	if probe := renderProbe(m.Runtime.Healthcheck); probe != "" {
		fmt.Fprintf(&b, "    readiness_probe=%s,\n", probe)
	}
	if len(m.Links) > 0 {
		parts := make([]string, 0, len(m.Links))
		for _, l := range m.Links {
			label := l.Label
			if label == "" {
				label = svc.Name
			}
			parts = append(parts, fmt.Sprintf("link(%s, %s)", starStr(l.URL), starStr(label)))
		}
		fmt.Fprintf(&b, "    links=[%s],\n", strings.Join(parts, ", "))
	}

	b.WriteString(")\n")
	return b.String(), nil
}

// serveCmd builds the run command, prefixing guarded sourcing of env files.
// .envrc is always attempted (harmless if absent); workspace/service files add more.
func serveCmd(m *config.ServiceManifest, ws *config.WorkspaceManifest) string {
	files := dedupe(append([]string{".envrc"}, append(append([]string{}, ws.Env.Files...), m.Env.Files...)...))
	if len(files) == 0 {
		return m.Runtime.Run.Command
	}
	var pre strings.Builder
	for _, f := range files {
		ref := shQuote(sourceRef(f))
		fmt.Fprintf(&pre, "[ -f %s ] && set -a && . %s && set +a; ", ref, ref)
	}
	return pre.String() + m.Runtime.Run.Command
}

func mergedEnv(layers ...map[string]string) map[string]string {
	out := map[string]string{}
	for _, l := range layers {
		for k, v := range l {
			out[k] = v
		}
	}
	return out
}

func renderProbe(h config.ServiceHealthcheck) string {
	period := h.PeriodSecs
	if period == 0 {
		period = 5
	}
	fails := h.FailureThreshold
	if fails == 0 {
		fails = 10
	}
	switch h.Type {
	case "exec":
		if h.Command == "" {
			return ""
		}
		return fmt.Sprintf("probe(exec=exec_action([%s, %s, %s]), period_secs=%d, failure_threshold=%d)",
			starStr("bash"), starStr("-c"), starStr(h.Command), period, fails)
	case "http":
		if h.Port == 0 {
			return ""
		}
		path := h.Path
		if path == "" {
			path = "/"
		}
		return fmt.Sprintf("probe(http_get=http_get_action(port=%d, path=%s), period_secs=%d, failure_threshold=%d)",
			h.Port, starStr(path), period, fails)
	default:
		return ""
	}
}

func triggerMode(mode string) string {
	if strings.EqualFold(mode, "auto") {
		return "TRIGGER_MODE_AUTO"
	}
	return "TRIGGER_MODE_MANUAL"
}

func pyBool(b bool) string {
	if b {
		return "True"
	}
	return "False"
}

// starStr renders a Go string as a Starlark/Python double-quoted literal.
func starStr(s string) string {
	return fmt.Sprintf("%q", s)
}

func starList(items []string) string {
	parts := make([]string, len(items))
	for i, s := range items {
		parts[i] = starStr(s)
	}
	return strings.Join(parts, ", ")
}

// shQuote single-quotes a string for embedding in a shell command.
func shQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// sourceRef ensures a relative env-file path has a slash so the POSIX `.` builtin
// loads it from the run dir instead of searching $PATH (dash won't fall back to
// the cwd like bash does).
func sourceRef(f string) string {
	if strings.HasPrefix(f, "/") || strings.HasPrefix(f, "./") || strings.HasPrefix(f, "../") {
		return f
	}
	return "./" + f
}

func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func dedupe(items []string) []string {
	seen := map[string]bool{}
	var out []string
	for _, s := range items {
		if s == "" || seen[s] {
			continue
		}
		seen[s] = true
		out = append(out, s)
	}
	return out
}
