package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/socialviolation/devstack/internal/worktree"
)

// devstack wrote a block of instructions into the instruction files of each
// service repository, between these markers, and a legacy section before the
// markers existed. It writes neither now: `devstack prime` prints the same facts
// at each session start, so a committed copy only goes stale while reading
// exactly like a true one.
//
// The markers stay because devstack has to find what it left behind and remove
// it.
const (
	agentsSentinelBegin = "<!-- devstack:begin — generated by `devstack init`; do not edit between these markers -->"
	agentsSentinelEnd   = "<!-- devstack:end -->"
	legacyAgentsHeader  = "## Dev Stack (devstack MCP)"
	legacyPointerHeader = "## devstack (local dev services)"

	agentsFileName = "AGENTS.md"
)

// aiInstructionFiles are the instruction files coding agents read. devstack
// removes its own block from the ones a repository already has, and it creates
// none of them.
var aiInstructionFiles = []string{
	"CLAUDE.md",
	"GEMINI.md",
	".cursorrules",
	filepath.Join(".github", "copilot-instructions.md"),
}

const (
	actionRemoved   = "removed the devstack block"
	actionDeleted   = "file deleted"
	actionLeftAlone = "left alone"
)

// fileChange is what devstack did to one file, and why.
type fileChange struct {
	Rel    string
	Path   string
	Action string
	Reason string
}

// Changed reports whether this outcome wrote to the disk.
func (c fileChange) Changed() bool { return c.Action != actionLeftAlone }

// contentFile is one file devstack wrote into, with the legacy header it used
// in that file.
type contentFile struct {
	Rel    string
	Path   string
	Legacy string
}

func contentFiles(dir string) []contentFile {
	out := []contentFile{{Rel: agentsFileName, Path: filepath.Join(dir, agentsFileName), Legacy: legacyAgentsHeader}}
	for _, rel := range aiInstructionFiles {
		out = append(out, contentFile{Rel: rel, Path: filepath.Join(dir, rel), Legacy: legacyPointerHeader})
	}
	return out
}

// stripDir removes the devstack content from every instruction file in dir. It
// reports one line for each file it changed, and for each file that needs a
// human. A file with no devstack content is not reported, because a report of
// files nobody has to read is a report nobody reads.
func stripDir(dir string) []fileChange {
	var out []fileChange
	for _, f := range contentFiles(dir) {
		if c := stripFile(f); c != nil {
			out = append(out, *c)
		}
	}
	return out
}

// stripFile removes the devstack content from one file.
//
// It removes only what devstack wrote. Where the file holds a marker devstack
// can not pair, the end of the block is unknown, so devstack changes nothing and
// asks for a human. Where nothing but devstack content remains, the file goes.
func stripFile(f contentFile) *fileChange {
	data, err := os.ReadFile(f.Path)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return &fileChange{Rel: f.Rel, Path: f.Path, Action: actionLeftAlone, Reason: "devstack can not read it: " + err.Error()}
	}

	s := string(data)
	if !hasDevstackContent(s, f.Legacy) {
		return nil
	}
	if !sentinelPairsAreSound(s) {
		return &fileChange{Rel: f.Rel, Path: f.Path, Action: actionLeftAlone,
			Reason: "a devstack marker has no pair, so the end of the block is unknown. Remove the block by hand"}
	}

	rest := tidyMarkdown(stripLegacySections(removeSentinelBlocks(s), f.Legacy))
	if rest == s {
		return nil
	}
	if rest == "" {
		if err := os.Remove(f.Path); err != nil {
			return &fileChange{Rel: f.Rel, Path: f.Path, Action: actionLeftAlone, Reason: "devstack can not delete it: " + err.Error()}
		}
		return &fileChange{Rel: f.Rel, Path: f.Path, Action: actionDeleted, Reason: "it held devstack content only"}
	}
	if err := os.WriteFile(f.Path, []byte(rest), 0644); err != nil {
		return &fileChange{Rel: f.Rel, Path: f.Path, Action: actionLeftAlone, Reason: "devstack can not write it: " + err.Error()}
	}
	return &fileChange{Rel: f.Rel, Path: f.Path, Action: actionRemoved}
}

// hasDevstackContent reports whether s holds anything devstack wrote.
func hasDevstackContent(s, legacy string) bool {
	if strings.Contains(s, agentsSentinelBegin) || strings.Contains(s, agentsSentinelEnd) {
		return true
	}
	_, found := stripOneLegacySection(s, legacy)
	return found
}

// sentinelPairsAreSound reports whether every marker in s is part of a complete
// begin-end pair, in that order.
//
// Anything else means devstack can not say where its block ends, and a guess
// deletes text a human wrote. A truncated block is rare and a lost paragraph is
// not, so devstack stops instead.
func sentinelPairsAreSound(s string) bool {
	for {
		begin := strings.Index(s, agentsSentinelBegin)
		end := strings.Index(s, agentsSentinelEnd)
		switch {
		case begin == -1 && end == -1:
			return true
		case begin == -1 || end == -1:
			return false
		case end < begin:
			return false
		}
		s = s[end+len(agentsSentinelEnd):]
	}
}

// removeSentinelBlocks removes every complete marker-wrapped block from s.
func removeSentinelBlocks(s string) string {
	for {
		begin := strings.Index(s, agentsSentinelBegin)
		if begin == -1 {
			return s
		}
		rel := strings.Index(s[begin:], agentsSentinelEnd)
		if rel == -1 {
			return s
		}
		s = joinSeam(s[:begin], s[begin+rel+len(agentsSentinelEnd):])
	}
}

// stripLegacySections removes every unsentinelled devstack section named by
// header, from that header up to (but not including) the next "## " header at
// column 0, or EOF if none — so a following section such as "## BEADS" survives.
func stripLegacySections(s, header string) string {
	for {
		stripped, removed := stripOneLegacySection(s, header)
		if !removed {
			return s
		}
		s = stripped
	}
}

func stripOneLegacySection(s, header string) (string, bool) {
	start := findHeaderLine(s, header)
	if start == -1 {
		return s, false
	}
	rest := s[start+len(header):]
	if i := strings.Index(rest, "\n## "); i != -1 {
		return joinSeam(s[:start], rest[i+1:]), true
	}
	return joinSeam(s[:start], ""), true
}

// findHeaderLine gives the offset of the first line that is header and nothing
// else, or -1. The header must fill the line: "## devstack (local dev services)
// and MY OWN NOTES" is a heading a human extended, and everything below it is
// theirs.
func findHeaderLine(s, header string) int {
	for at := 0; at < len(s); {
		i := strings.Index(s[at:], header)
		if i == -1 {
			return -1
		}
		start := at + i
		rest := s[start+len(header):]
		if (start == 0 || s[start-1] == '\n') && (rest == "" || rest[0] == '\n' || rest[0] == '\r') {
			return start
		}
		at = start + 1
	}
	return -1
}

// joinSeam closes the gap a removed block leaves, with one blank line between
// what remains on each side. It trims newlines only, so a line a human wrote
// keeps every character of it.
func joinSeam(before, after string) string {
	b := strings.TrimRight(before, "\n")
	a := strings.TrimLeft(after, "\n")
	switch {
	case b == "":
		return a
	case a == "":
		return b
	}
	return b + "\n\n" + a
}

// tidyMarkdown gives the remaining text one trailing newline, and no leading
// blank line where the removed block was at the top. It returns "" for a file
// that now holds whitespace only.
func tidyMarkdown(s string) string {
	s = strings.TrimLeft(s, "\n")
	s = strings.TrimRight(s, " \t\n")
	if strings.TrimSpace(s) == "" {
		return ""
	}
	return s + "\n"
}

// repoRoot is the root of a git repository devstack has to sweep, with the
// index in dirs of the directory that led devstack to it. The caller keeps the
// name and the stack of that directory, so the report can say where the root
// came from.
type repoRoot struct {
	Root string
	From int
}

// repoRootsOf names the root of the git repository that holds each directory in
// dirs, and that dirs does not hold already.
//
// An older devstack wrote its block at the root of each git repository. devstack
// sweeps service directories. Where a service sits in a subdirectory of its
// repository, nothing sweeps the root, and the block stays there.
//
// A directory that no git repository holds contributes no root. Two directories
// of one repository contribute that root once.
func repoRootsOf(dirs []string) []repoRoot {
	seen := map[string]bool{}
	tops := make([]string, len(dirs))
	for i, dir := range dirs {
		isRoot, top := worktree.IsRoot(dir)
		tops[i] = top
		if isRoot {
			seen[top] = true
		}
	}

	var out []repoRoot
	for i, top := range tops {
		if top == "" || seen[top] {
			continue
		}
		seen[top] = true
		out = append(out, repoRoot{Root: top, From: i})
	}
	return out
}

// residueFile is one file that still holds content devstack wrote.
type residueFile struct {
	Path       string
	NeedsHuman bool
}

// scanResidue reports the files under dir that still hold devstack content. It
// reads and changes nothing, so `upgrade` and `workspace doctor` can say what
// `devstack migrate` will clean.
func scanResidue(dir string) []residueFile {
	var out []residueFile
	for _, f := range contentFiles(dir) {
		data, err := os.ReadFile(f.Path)
		if err != nil || !hasDevstackContent(string(data), f.Legacy) {
			continue
		}
		out = append(out, residueFile{Path: f.Path, NeedsHuman: !sentinelPairsAreSound(string(data))})
	}
	return out
}

// describeChange is one report line: what devstack did to a file, and why.
func describeChange(c fileChange) string {
	line := fmt.Sprintf("      %-24s %s", c.Rel, c.Action)
	if c.Reason != "" {
		line += ": " + c.Reason
	}
	return line
}
