package cmd

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/socialviolation/devstack/internal/stack"
	"github.com/socialviolation/devstack/internal/workspace"
)

func TestRegenerateHostTiltfileEmptyDrains(t *testing.T) {
	tmpHome := t.TempDir()
	t.Setenv("HOME", tmpHome)

	path, err := regenerateHostTiltfile()
	if err != nil {
		t.Fatalf("regenerateHostTiltfile (no active): %v", err)
	}
	if path != filepath.Join(workspace.HostTiltDir(), "Tiltfile") {
		t.Fatalf("unexpected host Tiltfile path: %s", path)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read host Tiltfile: %v", err)
	}
	if !strings.Contains(string(data), "GENERATED BY devstack") {
		t.Fatalf("empty host Tiltfile is not a valid header-only file:\n%s", data)
	}
	if strings.Contains(string(data), "local_resource(") {
		t.Fatalf("empty host Tiltfile unexpectedly contains resources:\n%s", data)
	}
}

func TestRegenerateHostTiltfilePrefixesActiveWorkspaceAndStack(t *testing.T) {
	rec, port := buildStackScenario(t)
	_ = port

	if err := workspace.SetWorkspaceActive("navexa", true); err != nil {
		t.Fatalf("activate workspace: %v", err)
	}
	if err := stack.SetActive("navexa", rec.Name, true); err != nil {
		t.Fatalf("activate stack: %v", err)
	}

	path, err := regenerateHostTiltfile()
	if err != nil {
		t.Fatalf("regenerateHostTiltfile: %v", err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read host Tiltfile: %v", err)
	}
	out := string(data)

	if !strings.Contains(out, `"navexa:backend"`) {
		t.Fatalf("host Tiltfile missing workspace-prefixed base resource navexa:backend:\n%s", out)
	}
	if !strings.Contains(out, `"navexa:frontend"`) {
		t.Fatalf("host Tiltfile missing workspace-prefixed base resource navexa:frontend:\n%s", out)
	}
	if !strings.Contains(out, `"navexa:backend:feat"`) {
		t.Fatalf("host Tiltfile missing prefixed+namespaced stack resource navexa:backend:feat:\n%s", out)
	}
}

func TestRegenerateHostTiltfileExcludesInactiveWorkspace(t *testing.T) {
	buildStackScenario(t)

	path, err := regenerateHostTiltfile()
	if err != nil {
		t.Fatalf("regenerateHostTiltfile: %v", err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read host Tiltfile: %v", err)
	}
	if strings.Contains(string(data), "navexa:backend") {
		t.Fatalf("inactive workspace leaked into host Tiltfile:\n%s", data)
	}
}
