package cmd

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/viper"

	"github.com/socialviolation/devstack/internal/config"
	"github.com/socialviolation/devstack/internal/gitinfo"
	"github.com/socialviolation/devstack/internal/stack"
	"github.com/socialviolation/devstack/internal/tilt"
	"github.com/socialviolation/devstack/internal/workspace"
)

// primeCharBudget is the ceiling a SessionStart hook will accept before Claude
// Code truncates the output to a file and shows a preview instead. Everything
// here is generated per session, so it earns its place against that budget or it
// belongs behind `devstack help`.
const primeCharBudget = 9000

var primeCmd = &cobra.Command{
	Use:   "prime",
	Short: "Brief an agent on where it is, what is running, and which stack it is probably here for",
	Long: `Print the session-start briefing for this directory: the workspace and service
you are in, which feature stack the checkout belongs to, what is running right
now, and what this workspace actually uses.

Generated by the binary at session start, so it cannot go stale the way a
committed AGENTS.md does — install a new devstack and every workspace is briefed
correctly on its next session.

Wire it into Claude Code as a SessionStart hook (.claude/settings.json):

  {
    "hooks": {
      "SessionStart": [
        {
          "matcher": "startup",
          "hooks": [{"type": "command", "command": "devstack prime --json"}]
        }
      ]
    }
  }

--json emits the hookSpecificOutput envelope the hook expects. Plain output is
for reading yourself.`,
	SilenceUsage: true,
	RunE:         runPrime,
}

func init() {
	rootCmd.AddCommand(primeCmd)
	primeCmd.Flags().Bool("json", false, "Emit the Claude Code SessionStart hookSpecificOutput envelope")
}

// workingStack is the stack a session is probably for, and why devstack thinks
// so. Certain means the working directory settles it; otherwise it is a
// suggestion the agent should confirm, because acting on the wrong stack edits
// the wrong worktree.
type workingStack struct {
	Rec     *stack.Record
	Reason  string
	Certain bool
}

// inferWorkingStack picks the stack this session is for, strongest signal first:
// the worktree you are standing in settles it outright; a checked-out branch
// that matches a stack's is near-certain; a single stack overlaying this service
// is a guess worth offering. Anything else is left ambiguous on purpose — a
// confident wrong answer sends an agent to edit a worktree nobody asked about.
func inferWorkingStack(ws *workspace.Workspace, service, branch string) *workingStack {
	if _, rec, err := stack.DetectFromCwd(); err == nil && rec != nil {
		return &workingStack{Rec: rec, Reason: "you are in the worktree of this stack", Certain: true}
	}

	recs, err := stack.LoadStore(ws.Name)
	if err != nil || len(recs) == 0 {
		return nil
	}

	if branch != "" {
		bare := strings.TrimSuffix(branch, "*")
		for i := range recs {
			if recs[i].Branch != "" && recs[i].Branch == bare {
				return &workingStack{Rec: &recs[i], Reason: "the branch of this stack is checked out here", Certain: true}
			}
		}
	}

	if service == "" {
		return nil
	}
	var candidates []*stack.Record
	for i := range recs {
		if containsString(recs[i].Overlay, service) {
			candidates = append(candidates, &recs[i])
		}
	}
	if len(candidates) == 1 {
		return &workingStack{Rec: candidates[0], Reason: "this is the only stack that runs " + service}
	}
	return nil
}

func runPrime(cmd *cobra.Command, args []string) error {
	asJSON, _ := cmd.Flags().GetBool("json")

	body, err := buildPrime()
	if err != nil {
		// A briefing that cannot resolve must not fail the session it is briefing.
		body = fmt.Sprintf("devstack: could not brief this directory: %v", err)
	}
	if len(body) > primeCharBudget {
		body = body[:primeCharBudget] + "\n… truncated; run: devstack status"
	}

	if !asJSON {
		fmt.Println(body)
		return nil
	}
	out := map[string]any{
		"hookSpecificOutput": map[string]any{
			"hookEventName":     "SessionStart",
			"additionalContext": body,
		},
	}
	enc := json.NewEncoder(os.Stdout)
	return enc.Encode(out)
}

func buildPrime() (string, error) {
	ws, err := resolveWorkspace(viper.GetString("workspace"))
	if err != nil {
		if base, _, derr := stack.DetectFromCwd(); derr == nil && base != nil {
			ws = base
		} else {
			return "", err
		}
	}
	rw, err := config.ResolveWorkspace(ws.Path)
	if err != nil {
		return "", err
	}

	service := ""
	if cwd, cerr := os.Getwd(); cerr == nil {
		if id, ierr := config.ResolveIdentity(cwd); ierr == nil {
			service = id.ServiceName
		}
	}

	repo := ""
	if svc, ok := rw.Services[service]; ok && service != "" {
		repo = svc.RepoPath
	}
	branch := ""
	if repo != "" {
		branch = gitinfo.ReadAll(map[string]string{repo: repo})[repo].Label()
	}

	working := inferWorkingStack(ws, service, branch)
	if working != nil && working.Certain {
		if wt, ok := working.Rec.Worktrees[service]; ok && wt != "" {
			repo = wt
			branch = gitinfo.ReadAll(map[string]string{wt: wt})[wt].Label()
		}
	}

	var b strings.Builder
	writePrimeWhatThisIs(&b)
	writePrimeIdentity(&b, ws, service, repo, branch, working)
	writePrimeInstances(&b, ws, rw, service, working)
	writePrimeApplies(&b, ws, rw)
	writePrimeReload(&b, rw, service, working)
	writePrimeNotes(&b, rw, service)
	b.WriteString("\nreference: devstack status · devstack help <command> · devstack stack list\n")
	return strings.TrimRight(b.String(), "\n"), nil
}

func writePrimeIdentity(b *strings.Builder, ws *workspace.Workspace, service, repo, branch string, working *workingStack) {
	fmt.Fprintf(b, "devstack · workspace %s", ws.Name)
	if service != "" {
		fmt.Fprintf(b, " · service %s", service)
	}
	if working != nil && working.Certain {
		fmt.Fprintf(b, " · stack %s\n", working.Rec.Name)
	} else {
		b.WriteString(" · base\n")
	}
	if working == nil {
		return
	}
	fmt.Fprintf(b, "  working on  %s (%s)\n", working.Rec.Name, working.Reason)
	if note := firstLine(working.Rec.Note, 120); note != "" {
		fmt.Fprintf(b, "  purpose %s\n", note)
	}
	if !working.Certain {
		fmt.Fprintf(b, "  This is NOT confirmed. The worktree of this stack is %s.\n  Ask the user before you start this task.\n",
			working.Rec.Worktrees[service])
		return
	}
	if service != "" {
		fmt.Fprintf(b, "  Your changes here stay on the branch of this stack. To restart this copy, run:\n    devstack restart %s --stack %s\n",
			service, working.Rec.Name)
	}
}

func writePrimeApplies(b *strings.Builder, ws *workspace.Workspace, rw *config.ResolvedWorkspace) {
	var lines []string
	if envs := sortedEnvNames(rw); len(envs) > 0 {
		lines = append(lines, fmt.Sprintf("  environments  %s (active: %s) — devstack env which",
			strings.Join(envs, ", "), orDash(rw.Manifest.Workspace.Env)))
	}
	if n := countHooks(ws, rw); n > 0 {
		lines = append(lines, fmt.Sprintf("  hooks         %d declared, run automatically on stack/service lifecycle — devstack hooks list", n))
	}
	if rw.Manifest.Observability.IsEnabled() {
		lines = append(lines, fmt.Sprintf("  observability %s — devstack otel traces", rw.Manifest.Observability.ResolvedBackend()))
	}
	if len(lines) == 0 {
		return
	}
	b.WriteString("\nthis workspace uses:\n")
	for _, l := range lines {
		b.WriteString(l + "\n")
	}
}

func sortedEnvNames(rw *config.ResolvedWorkspace) []string {
	names := make([]string, 0, len(rw.Manifest.Environments))
	for n := range rw.Manifest.Environments {
		names = append(names, n)
	}
	sort.Strings(names)
	return names
}

// countHooks counts every hook this workspace declares, workspace-level and
// per-service, so the briefing can say whether lifecycle automation runs here.
func countHooks(ws *workspace.Workspace, rw *config.ResolvedWorkspace) int {
	n := len(rw.Manifest.Hooks)
	for _, svc := range rw.Services {
		if svc.Manifest != nil {
			n += len(svc.Manifest.Hooks)
		}
	}
	return n
}

// writePrimeWhatThisIs states the few facts an agent that has never met devstack
// will otherwise get wrong. Each line earns its place by naming a wrong
// conclusion it prevents, not by describing a feature: that a service has
// several running copies, that "stopped" is a registration state rather than a
// fault, and that none of this is safe to point at production. Everything else
// about devstack is a `devstack help` away and does not belong in every session.
func writePrimeWhatThisIs(b *strings.Builder) {
	b.WriteString("devstack manages the local development services on this machine. It starts and stops the services,\n")
	b.WriteString("it collects their logs, and it sets their environment variables.\n\n")
	b.WriteString("CAUTION: Use devstack only for local development. Do not use it with a staging or a production system.\n\n")
	b.WriteString("These are the devstack terms in this text:\n")
	b.WriteString("  workspace  the set of repositories that run together\n")
	b.WriteString("  service    one process that devstack runs\n")
	b.WriteString("  base       your normal checkout. A command uses base if you do not give --stack\n")
	b.WriteString("  stack      a parallel copy of some services. Each stack has its own branch, its own directory, and its own ports\n")
	b.WriteString("  worktree   the directory of a stack. Git checks out the branch of the stack in this directory\n")
	b.WriteString("One service can run more than one time. base runs one copy, and each stack runs another copy.\n")
	b.WriteString("Each copy has a different port. Run `devstack status` before you decide that a service is down.\n")
	b.WriteString("The state \"stopped\" means that the service is registered but not started. It does not mean that the service is broken.\n\n")
	b.WriteString("To work on a stack, change to the directory of that stack. The branch is already checked out there.\n")
	b.WriteString("Do not use `git checkout` in your normal checkout. That changes base, and it does not change the stack.\n\n")
}

// writePrimeReload gives the reload verdict for the service in hand rather than
// the general rule, because the general rule is what an agent skips. A service
// that does not self-watch keeps executing old code after an edit, and the
// resulting "my fix did nothing" is expensive to debug from the wrong end.
func writePrimeReload(b *strings.Builder, rw *config.ResolvedWorkspace, service string, working *workingStack) {
	if service == "" {
		return
	}
	svc, ok := rw.Services[service]
	if !ok || svc.Manifest == nil {
		return
	}
	runCmd := strings.TrimSpace(svc.Manifest.Runtime.Run.Command)
	if runCmd == "" {
		return
	}

	target := service
	if working != nil && working.Certain {
		target += " --stack " + working.Rec.Name
	}

	switch {
	case looksHotReloading(runCmd) || looksHotReloading(resolveRunScript(runCmd, svc.RepoPath)):
		fmt.Fprintf(b, "\n%s reloads automatically (run command: `%s`). Your code changes apply without a restart.\n", service, runCmd)
	case len(svc.Manifest.Runtime.Watch) > 0:
		fmt.Fprintf(b, "\n%s restarts automatically, because runtime.watch is set. Your code changes apply without a restart.\n", service)
	default:
		fmt.Fprintf(b, "\n%s does not reload automatically (run command: `%s`). After you change the code, it runs the old code.\n", service, runCmd)
		fmt.Fprintf(b, "To load your changes, run:\n  devstack restart %s\n", target)
	}
	b.WriteString("If you change the configuration or an environment variable, you must restart the service.\n")
}

// writePrimeInstances is the one table that answers the three questions an agent
// has about the service in front of it: where is it running, on which port, and
// what is that copy for. Base and every stack are the same kind of thing — an
// instance — so splitting them across two blocks made the reader join them up,
// and left base's own port stated nowhere at all.
func writePrimeInstances(b *strings.Builder, ws *workspace.Workspace, rw *config.ResolvedWorkspace, service string, working *workingStack) {
	view, err := tilt.NewClient("localhost", workspace.HostTiltPort).GetView()
	if err != nil {
		b.WriteString("\nThe daemon is not started. To start it, run: `devstack workspace up`\n")
		return
	}

	states := map[string]string{}
	total := 0
	for _, r := range view.UiResources {
		name := r.Metadata.Name
		if !strings.HasPrefix(name, ws.Name+":") {
			continue
		}
		st := serviceStatus(r)
		if st == "running" {
			total++
		}
		states[strings.TrimPrefix(name, ws.Name+":")] = st
	}
	fmt.Fprintf(b, "\nlive: %s in the daemon on port %d\n", pluralRun(total), workspace.HostTiltPort)
	if service == "" {
		return
	}

	type instance struct{ name, port, state, branch, dir, note string }

	rows := []instance{{name: "base", port: "-", state: orDash(states[service])}}
	if svc, ok := rw.Services[service]; ok {
		rows[0].dir = svc.RepoPath
		if svc.Manifest != nil {
			if p, ok := svc.Manifest.Ports["http"]; ok {
				rows[0].port = fmt.Sprintf(":%d", p)
			}
		}
	}

	recs, _ := stack.LoadStore(ws.Name)
	sort.Slice(recs, func(i, j int) bool { return recs[i].Name < recs[j].Name })
	for _, rec := range recs {
		if !containsString(rec.Overlay, service) {
			continue
		}
		row := instance{name: rec.Name, port: "-", state: "inactive", note: firstLine(rec.Note, 74)}
		if p, ok := rec.Ports[stack.QualifyPortKey(service, "http")]; ok {
			row.port = fmt.Sprintf(":%d", p)
		}
		if st, ok := states[service+":"+rec.Name]; ok {
			row.state = st
		}
		row.dir = rec.Worktrees[service]
		rows = append(rows, row)
	}

	// The branch is read from each checkout rather than taken from the stack
	// record: a service pulled into an overlay because it calls a changed one is
	// detached at HEAD, not on the branch of the stack, and telling an agent
	// otherwise sends it to commit somewhere that does not exist.
	dirs := map[string]string{}
	for _, r := range rows {
		if r.dir != "" {
			dirs[r.dir] = r.dir
		}
	}
	labels := gitinfo.ReadAll(dirs)
	for i := range rows {
		if rows[i].dir != "" {
			rows[i].branch = labels[rows[i].dir].Label()
		}
	}

	fmt.Fprintf(b, "\n%s runs as %s:\n", service, pluralCopy(len(rows)))
	for _, r := range rows {
		marker := " "
		if working != nil && working.Rec != nil && working.Rec.Name == r.name {
			marker = "▸"
		} else if r.name == "base" && working == nil {
			marker = "▸"
		}
		fmt.Fprintf(b, "  %s %-12s %-8s %-9s branch %s\n", marker, r.name, r.port, r.state, orDash(truncateCell(r.branch, 46)))
		if r.dir != "" {
			fmt.Fprintf(b, "      %s\n", r.dir)
		}
		if r.note != "" {
			fmt.Fprintf(b, "      %s\n", r.note)
		}
	}
	b.WriteString("  ▸ is the checkout that you are in. To use the copy from a stack, connect to its port,\n  or add `--stack <name>` to a command.\n")
}

// pluralRun and pluralCopy keep the count grammatical. "1 service(s)" makes a
// reader stop and parse, which is the opposite of what a briefing is for.
func pluralRun(n int) string {
	if n == 1 {
		return "1 service runs"
	}
	return fmt.Sprintf("%d services run", n)
}

func pluralCopy(n int) string {
	if n == 1 {
		return "1 copy"
	}
	return fmt.Sprintf("%d copies", n)
}

// primeDocsBudget bounds the team-authored context so a long document cannot
// push the briefing past the limit the session-start hook imposes. The
// briefing's own content is fixed and small; this is the only part a workspace
// can grow without limit.
const primeDocsBudget = 4000

// writePrimeNotes prints the prose a team declared for this workspace and this
// service. It is inlined rather than linked because a reference is only read by
// an agent that decides to read it, and a team that wrote the document intended
// it to be read. Anything past the budget is clipped and names its own path.
func writePrimeNotes(b *strings.Builder, rw *config.ResolvedWorkspace, service string) {
	docs := config.ResolveContextDocs(rw, service)
	if len(docs) == 0 {
		return
	}
	remaining := primeDocsBudget
	for _, d := range docs {
		if d.Missing {
			fmt.Fprintf(b, "\nNOTE: %s declares %s, and that file is not on disk.\n", config.WorkspaceManifestFileName, d.Path)
			continue
		}
		if remaining <= 0 {
			fmt.Fprintf(b, "\nmore context for this workspace: %s\n", d.Path)
			continue
		}
		fmt.Fprintf(b, "\n%s notes — %s\n", d.Title(), d.Path)
		body := d.Clip(remaining)
		remaining -= len(body)
		for _, line := range strings.Split(body, "\n") {
			fmt.Fprintf(b, "  %s\n", line)
		}
	}
}
