package cmd

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/viper"

	"github.com/socialviolation/devstack/internal/config"
	"github.com/socialviolation/devstack/internal/gitinfo"
	"github.com/socialviolation/devstack/internal/stack"
	"github.com/socialviolation/devstack/internal/tilt"
	"github.com/socialviolation/devstack/internal/workspace"
)

// primeCharBudget is the ceiling a SessionStart hook will accept before Claude
// Code truncates the output to a file and shows a preview instead. Everything
// here is generated per session, so it earns its place against that budget or it
// belongs behind `devstack help`.
const primeCharBudget = 9000

var primeCmd = &cobra.Command{
	Use:   "prime",
	Short: "Brief an agent on where it is, what is running, and which stack it is probably here for",
	Long: `Print the session-start briefing for this directory: the workspace and service
you are in, which feature stack the checkout belongs to, what is running right
now, and what this workspace actually uses.

Generated by the binary at session start, so it cannot go stale the way a
committed AGENTS.md does — install a new devstack and every workspace is briefed
correctly on its next session.

Wire it into Claude Code as a SessionStart hook (.claude/settings.json):

  {
    "hooks": {
      "SessionStart": [
        {
          "matcher": "startup",
          "hooks": [{"type": "command", "command": "devstack prime --json"}]
        }
      ]
    }
  }

--json emits the hookSpecificOutput envelope the hook expects. Plain output is
for reading yourself.`,
	SilenceUsage: true,
	RunE:         runPrime,
}

func init() {
	rootCmd.AddCommand(primeCmd)
	primeCmd.Flags().Bool("json", false, "Emit the Claude Code SessionStart hookSpecificOutput envelope")
}

// workingStack is the stack a session is probably for, and why devstack thinks
// so. Certain means the working directory settles it; otherwise it is a
// suggestion the agent should confirm, because acting on the wrong stack edits
// the wrong worktree.
type workingStack struct {
	Rec     *stack.Record
	Reason  string
	Certain bool
}

// inferWorkingStack picks the stack this session is for, strongest signal first:
// the worktree you are standing in settles it outright; a checked-out branch
// that matches a stack's is near-certain; a single stack overlaying this service
// is a guess worth offering. Anything else is left ambiguous on purpose — a
// confident wrong answer sends an agent to edit a worktree nobody asked about.
func inferWorkingStack(ws *workspace.Workspace, service, branch string) *workingStack {
	if _, rec, err := stack.DetectFromCwd(); err == nil && rec != nil {
		return &workingStack{Rec: rec, Reason: "you are inside its worktree", Certain: true}
	}

	recs, err := stack.LoadStore(ws.Name)
	if err != nil || len(recs) == 0 {
		return nil
	}

	if branch != "" {
		bare := strings.TrimSuffix(branch, "*")
		for i := range recs {
			if recs[i].Branch != "" && recs[i].Branch == bare {
				return &workingStack{Rec: &recs[i], Reason: "its branch is checked out here", Certain: true}
			}
		}
	}

	if service == "" {
		return nil
	}
	var candidates []*stack.Record
	for i := range recs {
		if containsString(recs[i].Overlay, service) {
			candidates = append(candidates, &recs[i])
		}
	}
	if len(candidates) == 1 {
		return &workingStack{Rec: candidates[0], Reason: "the only stack that runs " + service}
	}
	return nil
}

func runPrime(cmd *cobra.Command, args []string) error {
	asJSON, _ := cmd.Flags().GetBool("json")

	body, err := buildPrime()
	if err != nil {
		// A briefing that cannot resolve must not fail the session it is briefing.
		body = fmt.Sprintf("devstack: could not brief this directory: %v", err)
	}
	if len(body) > primeCharBudget {
		body = body[:primeCharBudget] + "\n… truncated; run: devstack status"
	}

	if !asJSON {
		fmt.Println(body)
		return nil
	}
	out := map[string]any{
		"hookSpecificOutput": map[string]any{
			"hookEventName":     "SessionStart",
			"additionalContext": body,
		},
	}
	enc := json.NewEncoder(os.Stdout)
	return enc.Encode(out)
}

func buildPrime() (string, error) {
	ws, err := resolveWorkspace(viper.GetString("workspace"))
	if err != nil {
		if base, _, derr := stack.DetectFromCwd(); derr == nil && base != nil {
			ws = base
		} else {
			return "", err
		}
	}
	rw, err := config.ResolveWorkspace(ws.Path)
	if err != nil {
		return "", err
	}

	service := ""
	if cwd, cerr := os.Getwd(); cerr == nil {
		if id, ierr := config.ResolveIdentity(cwd); ierr == nil {
			service = id.ServiceName
		}
	}

	repo := ""
	if svc, ok := rw.Services[service]; ok && service != "" {
		repo = svc.RepoPath
	}
	branch := ""
	if repo != "" {
		branch = gitinfo.ReadAll(map[string]string{repo: repo})[repo].Label()
	}

	working := inferWorkingStack(ws, service, branch)
	if working != nil && working.Certain {
		if wt, ok := working.Rec.Worktrees[service]; ok && wt != "" {
			repo = wt
			branch = gitinfo.ReadAll(map[string]string{wt: wt})[wt].Label()
		}
	}

	var b strings.Builder
	writePrimeIdentity(&b, ws, service, repo, branch, working)
	writePrimeLive(&b, ws, service)
	writePrimeStacks(&b, ws, service, working)
	writePrimeApplies(&b, ws, rw)
	b.WriteString("\nreference: devstack status · devstack help <command> · devstack stack list\n")
	return strings.TrimRight(b.String(), "\n"), nil
}

func writePrimeIdentity(b *strings.Builder, ws *workspace.Workspace, service, repo, branch string, working *workingStack) {
	fmt.Fprintf(b, "devstack · workspace %s", ws.Name)
	if service != "" {
		fmt.Fprintf(b, " · service %s", service)
	}
	if working != nil && working.Certain {
		fmt.Fprintf(b, " · stack %s\n", working.Rec.Name)
	} else {
		b.WriteString(" · base\n")
	}
	if repo != "" {
		fmt.Fprintf(b, "  repo    %s\n", repo)
	}
	if branch != "" {
		fmt.Fprintf(b, "  branch  %s\n", branch)
	}

	if working == nil {
		return
	}
	fmt.Fprintf(b, "  working on  %s (%s)\n", working.Rec.Name, working.Reason)
	if note := firstLine(working.Rec.Note, 120); note != "" {
		fmt.Fprintf(b, "  purpose %s\n", note)
	}
	if !working.Certain {
		fmt.Fprintf(b, "  NOT confirmed — its worktree is %s. Ask before assuming this is the task.\n",
			working.Rec.Worktrees[service])
		return
	}
	if service != "" {
		fmt.Fprintf(b, "  edits here stay on this stack's branch. Target it: devstack restart %s --stack %s\n",
			service, working.Rec.Name)
	}
}

func writePrimeLive(b *strings.Builder, ws *workspace.Workspace, service string) {
	view, err := tilt.NewClient("localhost", workspace.HostTiltPort).GetView()
	if err != nil {
		b.WriteString("\nlive: dev daemon is not running — start it: devstack workspace up\n")
		return
	}

	prefix := ws.Name + ":"
	running := 0
	var mine []string
	for _, r := range view.UiResources {
		name := r.Metadata.Name
		if !strings.HasPrefix(name, prefix) {
			continue
		}
		if serviceStatus(r) != "running" {
			continue
		}
		running++
		bare := strings.TrimPrefix(name, prefix)
		if service != "" && (bare == service || strings.HasPrefix(bare, service+":")) {
			mine = append(mine, bare)
		}
	}
	sort.Strings(mine)

	fmt.Fprintf(b, "\nlive: %d running in the host daemon on :%d\n", running, workspace.HostTiltPort)
	if len(mine) > 0 {
		fmt.Fprintf(b, "  %s: %s\n", service, strings.Join(mine, ", "))
		b.WriteString("  a service runs once per instance — base and each stack, on different ports\n")
	}
}

func writePrimeStacks(b *strings.Builder, ws *workspace.Workspace, service string, working *workingStack) {
	recs, err := stack.LoadStore(ws.Name)
	if err != nil || len(recs) == 0 {
		return
	}
	var rows []stack.Record
	for _, rec := range recs {
		if service == "" || containsString(rec.Overlay, service) {
			rows = append(rows, rec)
		}
	}
	if len(rows) == 0 {
		return
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].Name < rows[j].Name })

	label := "stacks in flight"
	if service != "" {
		label = "stacks running " + service
	}
	fmt.Fprintf(b, "\n%s:\n", label)
	for _, rec := range rows {
		marker := " "
		if working != nil && working.Rec != nil && working.Rec.Name == rec.Name {
			marker = "▸"
		}
		port := "-"
		if service != "" {
			if p, ok := rec.Ports[stack.QualifyPortKey(service, "http")]; ok {
				port = fmt.Sprintf(":%d", p)
			}
		}
		fmt.Fprintf(b, "  %s %-12s %-8s %s\n", marker, rec.Name, port, firstLine(rec.Note, 70))
	}
}

func writePrimeApplies(b *strings.Builder, ws *workspace.Workspace, rw *config.ResolvedWorkspace) {
	var lines []string
	if envs := sortedEnvNames(rw); len(envs) > 0 {
		lines = append(lines, fmt.Sprintf("  environments  %s (active: %s) — devstack env which",
			strings.Join(envs, ", "), orDash(rw.Manifest.Workspace.Env)))
	}
	if n := countHooks(ws, rw); n > 0 {
		lines = append(lines, fmt.Sprintf("  hooks         %d declared, run automatically on stack/service lifecycle — devstack hooks list", n))
	}
	if rw.Manifest.Observability.IsEnabled() {
		lines = append(lines, fmt.Sprintf("  observability %s — devstack otel traces", rw.Manifest.Observability.ResolvedBackend()))
	}
	if len(lines) == 0 {
		return
	}
	b.WriteString("\nthis workspace uses:\n")
	for _, l := range lines {
		b.WriteString(l + "\n")
	}
}

func sortedEnvNames(rw *config.ResolvedWorkspace) []string {
	names := make([]string, 0, len(rw.Manifest.Environments))
	for n := range rw.Manifest.Environments {
		names = append(names, n)
	}
	sort.Strings(names)
	return names
}

// countHooks counts every hook this workspace declares, workspace-level and
// per-service, so the briefing can say whether lifecycle automation runs here.
func countHooks(ws *workspace.Workspace, rw *config.ResolvedWorkspace) int {
	n := len(rw.Manifest.Hooks)
	for _, svc := range rw.Services {
		if svc.Manifest != nil {
			n += len(svc.Manifest.Hooks)
		}
	}
	return n
}
