package cmd

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/viper"

	"github.com/socialviolation/devstack/internal/config"
	"github.com/socialviolation/devstack/internal/gitinfo"
	"github.com/socialviolation/devstack/internal/selfcheck"
	"github.com/socialviolation/devstack/internal/stack"
	"github.com/socialviolation/devstack/internal/tilt"
	"github.com/socialviolation/devstack/internal/workspace"
)

// primeCharBudget is the ceiling a SessionStart hook will accept before Claude
// Code truncates the output to a file and shows a preview instead. Everything
// here is generated per session, so it earns its place against that budget or it
// belongs behind `devstack <command> --help`.
const primeCharBudget = 9000

var primeCmd = &cobra.Command{
	Use:   "prime",
	Short: "Brief an agent on where it is, what runs, and which stack it is probably here for",
	Long: `Print the session-start briefing for this directory: the workspace and service
you are in, which feature stack the checkout belongs to, what runs right
now, and what this workspace uses.

Generated by the binary at session start, so it cannot go stale the way a
committed AGENTS.md does — install a new devstack and every workspace is briefed
correctly on its next session.

Wire it into Claude Code as a SessionStart hook (.claude/settings.json):

  {
    "hooks": {
      "SessionStart": [
        {
          "matcher": "startup",
          "hooks": [{"type": "command", "command": "devstack prime --json"}]
        }
      ]
    }
  }

--json emits the hookSpecificOutput envelope the hook expects. Plain output is
for reading yourself.`,
	SilenceUsage: true,
	RunE:         runPrime,
}

func init() {
	rootCmd.AddCommand(primeCmd)
	primeCmd.Flags().Bool("json", false, "Emit the Claude Code SessionStart hookSpecificOutput envelope")
}

// workingStack is the stack a session is probably for, and why devstack thinks
// so. Certain means the working directory settles it; otherwise it is a
// suggestion the agent should confirm, because acting on the wrong stack edits
// the wrong worktree.
type workingStack struct {
	Rec     *stack.Record
	Reason  string
	Certain bool
}

// inferWorkingStack picks the stack this session is for, strongest signal first:
// the worktree you are standing in settles it outright; a checked-out branch
// that matches a stack's is near-certain; a single stack overlaying this service
// is a guess worth offering. Anything else is left ambiguous on purpose — a
// confident wrong answer sends an agent to edit a worktree nobody asked about.
func inferWorkingStack(ws *workspace.Workspace, service, branch string) *workingStack {
	if _, rec, err := stack.DetectFromCwd(); err == nil && rec != nil {
		return &workingStack{Rec: rec, Reason: "you are in the worktree of this stack", Certain: true}
	}

	recs, err := stack.LoadStore(ws.Name)
	if err != nil || len(recs) == 0 {
		return nil
	}

	if branch != "" {
		bare := strings.TrimSuffix(branch, "*")
		for i := range recs {
			if recs[i].Branch != "" && recs[i].Branch == bare {
				return &workingStack{Rec: &recs[i], Reason: "the branch of this stack is checked out here", Certain: true}
			}
		}
	}

	if service == "" {
		return nil
	}
	var candidates []*stack.Record
	for i := range recs {
		if containsString(recs[i].Overlay, service) {
			candidates = append(candidates, &recs[i])
		}
	}
	if len(candidates) == 1 {
		return &workingStack{Rec: candidates[0], Reason: "this is the only stack that runs " + service}
	}
	return nil
}

func runPrime(cmd *cobra.Command, args []string) error {
	asJSON, _ := cmd.Flags().GetBool("json")

	body, err := buildPrime()
	if err != nil {
		// A briefing that cannot resolve must not fail the session it is briefing.
		body = fmt.Sprintf("devstack: can not brief this directory: %v", err)
	}
	if len(body) > primeCharBudget {
		body = body[:primeCharBudget] + "\n… truncated; run: devstack status"
	}

	if !asJSON {
		fmt.Println(body)
		return nil
	}
	out := map[string]any{
		"hookSpecificOutput": map[string]any{
			"hookEventName":     "SessionStart",
			"additionalContext": body,
		},
	}
	enc := json.NewEncoder(os.Stdout)
	return enc.Encode(out)
}

func buildPrime() (string, error) {
	ws, err := resolveWorkspace(viper.GetString("workspace"))
	if err != nil {
		return "", err
	}
	rw, err := config.ResolveWorkspace(ws.Path)
	if err != nil {
		return "", err
	}

	service := ""
	if cwd, cerr := os.Getwd(); cerr == nil {
		if id, ierr := config.ResolveIdentity(cwd); ierr == nil {
			service = id.ServiceName
		}
	}

	repo := ""
	if svc, ok := rw.Services[service]; ok && service != "" {
		repo = svc.RepoPath
	}
	branch := ""
	if repo != "" {
		branch = gitinfo.ReadAll(map[string]string{repo: repo})[repo].Label()
	}

	// Where the caller physically is, read from the filesystem and nothing else.
	// Everything below distinguishes this from what devstack infers the session
	// is about: a stack whose branch matches, or the only stack that runs this
	// service, is a guess about intent and says nothing about the directory.
	here := "base"
	if _, rec, derr := stack.DetectFromCwd(); derr == nil && rec != nil {
		here = rec.Name
		if wt, ok := rec.Worktrees[service]; ok && wt != "" {
			repo = wt
			branch = gitinfo.ReadAll(map[string]string{wt: wt})[wt].Label()
		}
	}

	working := inferWorkingStack(ws, service, branch)

	var b strings.Builder
	writePrimeWhatThisIs(&b)
	writePrimeTerms(&b)

	section(&b, "WHERE YOU ARE")
	writePrimeIdentity(&b, ws, service, repo, branch, here, working)

	if service != "" {
		section(&b, "THIS SERVICE — "+service)
		writePrimeInstances(&b, ws, rw, service, here, working)
		writePrimeReload(&b, rw, service, working)
	}

	section(&b, "THIS WORKSPACE — "+ws.Name)
	writePrimeLiveCount(&b, ws)
	writePrimeApplies(&b, ws, rw)

	section(&b, "REFERENCE")
	b.WriteString("devstack status · devstack <command> --help · devstack stack list · devstack hooks list\n")
	return strings.TrimRight(b.String(), "\n"), nil
}

func writePrimeIdentity(b *strings.Builder, ws *workspace.Workspace, service, repo, branch, here string, working *workingStack) {
	fmt.Fprintf(b, "workspace %s", ws.Name)
	if service != "" {
		fmt.Fprintf(b, " · service %s", service)
	}
	if here == "base" {
		b.WriteString(" · base (not a stack)\n")
	} else {
		fmt.Fprintf(b, " · stack %s\n", here)
	}
	if here != "base" {
		// Standing in a stack. The fact that matters is that commits land on its
		// branch and not on base — the copies table below carries the rest.
		if rec, err := stack.Resolve(ws.Name, here); err == nil {
			if note := firstLine(rec.Note, 110); note != "" {
				fmt.Fprintf(b, "  purpose %s\n", note)
			}
			if e, ok := rec.LatestEntry(); ok {
				fmt.Fprintf(b, "  latest  %s  %s\n", e.At.Format("2006-01-02"), firstLine(e.Text, 100))
			}
		}
		b.WriteString("  Your changes here go on the branch of this stack, not on base.\n")
		return
	}

	if working == nil || working.Rec == nil || working.Rec.Name == here {
		return
	}
	fmt.Fprintf(b, "  possibly for  %s (%s)\n", working.Rec.Name, working.Reason)
	if note := firstLine(working.Rec.Note, 120); note != "" {
		fmt.Fprintf(b, "  purpose %s\n", note)
	}
	if e, ok := working.Rec.LatestEntry(); ok {
		fmt.Fprintf(b, "  latest  %s  %s\n", e.At.Format("2006-01-02"), firstLine(e.Text, 100))
	}
	fmt.Fprintf(b, "  You are not in that stack. The directory of that stack is %s.\n  Before you change any code, ask the user which stack this session is for.\n",
		orDash(working.Rec.Worktrees[service]))
}

func writePrimeApplies(b *strings.Builder, ws *workspace.Workspace, rw *config.ResolvedWorkspace) {
	var lines []string
	if envs := sortedEnvNames(rw); len(envs) > 0 {
		// A name says nothing about what selecting an environment does, so each
		// one carries its own description. The column is labelled because an
		// unlabelled "unset" beside an environment reads as "this environment
		// sets nothing" — which is the opposite of the truth, and was read that
		// way while an environment was live on a stack. What is unset is the
		// description, and the column heading is what says so.
		lines = append(lines, fmt.Sprintf("  environments  active: %s. Each environment sets different configuration values.", orDash(rw.Manifest.Workspace.Env)))
		lines = append(lines, fmt.Sprintf("                %-10s %s", "NAME", "PURPOSE"))
		for _, n := range envs {
			marker := " "
			if n == rw.Manifest.Workspace.Env {
				marker = "▸"
			}
			desc := firstLine(rw.Manifest.Environments[n].Description, 84)
			if desc == "" {
				desc = "(no purpose recorded)"
			}
			lines = append(lines, fmt.Sprintf("              %s %-10s %s", marker, n, desc))
		}
		lines = append(lines, "                Every environment sets values. A blank PURPOSE means only that nobody wrote down why.")
		lines = append(lines, "                To see the values one sets, run: devstack env which --service <svc>")
	}

	if n := countHooks(ws, rw); n > 0 {
		lines = append(lines, fmt.Sprintf("  hooks         %d declared, run automatically on stack and service lifecycle — devstack hooks list", n))
	}

	if rw.Manifest.Observability.IsEnabled() {
		// Which backend stores the telemetry is devstack's problem, not the
		// agent's: every query resolves the backend, endpoint and credentials
		// itself. Naming the product invites an agent to go around devstack and
		// query it directly, which is how you get a query that ignores the
		// workspace scoping.
		// The scoping sentence states what the commands do, which is not what
		// they were once documented to do: `otel traces` with no flag returns
		// every copy, base and stacks together, and `otel logs` has no --stack
		// at all. An agent told the opposite reads a stack's traffic as base's.
		lines = append(lines,
			"  telemetry     every copy sends traces and logs. Query them with `devstack otel traces` and `devstack otel logs`,",
			"                or with the investigate tool over MCP. The attribute devstack.stack identifies each copy.",
			"                `devstack otel traces` with no --stack returns every copy together, base and stacks. To get one,",
			"                give `--stack <name>`, or `--stack base` for base alone. `devstack otel logs` has no --stack:",
			"                use `--trace <id>` to get the logs of one execution.")
	}

	if len(lines) == 0 {
		return
	}
	for _, l := range lines {
		b.WriteString(l + "\n")
	}
}

func sortedEnvNames(rw *config.ResolvedWorkspace) []string {
	names := make([]string, 0, len(rw.Manifest.Environments))
	for n := range rw.Manifest.Environments {
		names = append(names, n)
	}
	sort.Strings(names)
	return names
}

// countHooks counts every hook this workspace declares, workspace-level and
// per-service, so the briefing can say whether lifecycle automation runs here.
func countHooks(ws *workspace.Workspace, rw *config.ResolvedWorkspace) int {
	n := len(rw.Manifest.Hooks)
	for _, svc := range rw.Services {
		if svc.Manifest != nil {
			n += len(svc.Manifest.Hooks)
		}
	}
	return n
}

// writePrimeWhatThisIs states the few facts an agent that has never met devstack
// will otherwise get wrong. Each line earns its place by naming a wrong
// conclusion it prevents, not by describing a feature: that a service has
// several running copies, that "stopped" is a registration state rather than a
// fault, and that none of this is safe to point at production. Everything else
// about devstack is a `devstack <command> --help` away and does not belong in
// every session.
func writePrimeWhatThisIs(b *strings.Builder) {
	b.WriteString("## DEVSTACK\n")
	b.WriteString("devstack manages the local development services on this machine. It starts and stops the services,\n")
	b.WriteString("it collects their logs, and it sets their environment variables.\n\n")
	b.WriteString("CAUTION: Use devstack only for local development. Do not use it with a staging or a production system.\n\n")
	b.WriteString("devstack is a CLI and an MCP server. The tools do the same work as the commands, and they share their names:\n")
	b.WriteString("status, start, stop, restart, stack_up, env_use. Use the one that your session has. Call the `environment` tool\n")
	b.WriteString("first. It lists the tools that this workspace has. The tools do not cover every command. If there is no tool\n")
	b.WriteString("for what you want, run the command in the shell. These have no tool: workspace up and down, ports,\n")
	b.WriteString("dependencies, group add and remove, stack config, and init.\n")
}

// writePrimeTerms defines the words the rest of the briefing uses. It is its own
// section because a reader who already knows them can skip it, and a reader who
// does not cannot parse a single line below without it.
func writePrimeTerms(b *strings.Builder) {
	section(b, "TERMS")
	b.WriteString("  workspace  the set of repositories that run together\n")
	b.WriteString("  service    one process that devstack runs\n")
	b.WriteString("  base       your normal checkout. If you do not give --stack, a command uses base\n")
	b.WriteString("  stack      a parallel copy of some services. Each stack has its own branch, its own directory, and its own ports\n")
	b.WriteString("  worktree   the directory of a stack. Git checks out the branch of the stack in this directory\n")
	b.WriteString("  copy       one running instance of a service. base runs one copy, and each stack runs another copy\n")
	b.WriteString("Each copy has a different port. Run `devstack status` before you decide that a service is down.\n")
	b.WriteString("To work on a stack, change to the directory of that stack. The branch is already checked out there.\n")
	b.WriteString("Do not use `git checkout` in your normal checkout. That command changes base, and it does not change the stack.\n")
	writePrimeStates(b)
}

// writePrimeStates defines every state word devstack prints, in one place. The
// same stack was reported "active" by one command, "idle" by another and
// "stopped" by this briefing, and nothing said the three were one state. A word
// that appears on no surface, or a surface that prints a word absent from here,
// is the drift returning — TestStateWordsAreDefinedOnce fails on both.
func writePrimeStates(b *strings.Builder) {
	b.WriteString("\nSTATES. A stack is up or down. A copy has one of these states:\n")
	b.WriteString("  running    the process is up and healthy\n")
	b.WriteString("  starting   devstack started it and it is not ready yet\n")
	b.WriteString("  building   its build step runs now\n")
	b.WriteString("  erroring   it failed. Read its logs\n")
	b.WriteString("  stopped    it is registered but not started. This is not a fault\n")
	b.WriteString("  disabled   somebody stopped it on purpose\n")
	b.WriteString("  down       the copy is not registered in the daemon. Usually its stack is down: run `devstack stack up <name>`\n")
	b.WriteString("  unknown    the daemon does not answer. Run `devstack workspace up`\n")
}

// writePrimeLiveCount reports how much of the workspace is up. The daemon runs
// one resource per copy, so the total counts copies and not services — a
// workspace of 16 services reporting "17 running" was read as more services than
// it has. The base and stack halves are split because they are the two numbers a
// reader is about to act on, and because `devstack status` prints the same split.
func writePrimeLiveCount(b *strings.Builder, ws *workspace.Workspace) {
	view, err := tilt.NewClient("localhost", workspace.HostTiltPort).GetView()
	if err != nil {
		b.WriteString("  daemon        not started. To start it, run: `devstack workspace up`\n")
		return
	}
	base, stacked := 0, 0
	for _, r := range view.UiResources {
		name := r.Metadata.Name
		if !strings.HasPrefix(name, ws.Name+":") || serviceStatus(r) != "running" {
			continue
		}
		if strings.Count(name, ":") > 1 {
			stacked++
		} else {
			base++
		}
	}
	// "in the daemon" would count the stopped copies too, and this counts only
	// the running ones. The briefing defines "stopped" as registered-not-started
	// on the same page, so the loose phrasing contradicted itself.
	fmt.Fprintf(b, "  live          %s now, on daemon port %d: %d in base, %d in stacks\n",
		pluralCopyRunning(base+stacked), workspace.HostTiltPort, base, stacked)
	writePrimeBuild(b)
}

// writePrimeBuild names the binary the session is talking to, and says so only
// when it is not the current one.
//
// This is the surface the check exists for. An agent inherits whichever devstack
// was on the path, and a stale one answers current commands with "unknown
// command" and serves MCP tool descriptions for tools that were renamed —
// neither of which names the cause. The briefing is the one place every session
// reads, so it is the one place worth saying it.
//
// It is also where the check refreshes: at most once a day, bounded by a short
// timeout, and silent on every failure. `devstack --version` reads what this
// leaves behind rather than paying for its own.
func writePrimeBuild(b *strings.Builder) {
	rev := buildRevision()
	if rev == "" {
		return
	}
	line := selfcheck.Refresh(modulePath(), rev).Describe(modulePath())
	if line == "" {
		return
	}
	fmt.Fprintf(b, "  build         %s\n", buildStamp())
	fmt.Fprintf(b, "                %s\n", line)
}

// writePrimeReload gives the reload verdict for the service in hand rather than
// the general rule, because the general rule is what an agent skips. A service
// that does not self-watch keeps executing old code after an edit, and the
// resulting "my fix did nothing" is expensive to debug from the wrong end.
func writePrimeReload(b *strings.Builder, rw *config.ResolvedWorkspace, service string, working *workingStack) {
	if service == "" {
		return
	}
	svc, ok := rw.Services[service]
	if !ok || svc.Manifest == nil {
		return
	}
	runCmd := strings.TrimSpace(svc.Manifest.Runtime.Run.Command)
	if runCmd == "" {
		return
	}

	target := service
	if working != nil && working.Certain {
		target += " --stack " + working.Rec.Name
	}

	switch {
	case looksHotReloading(runCmd) || looksHotReloading(resolveRunScript(runCmd, svc.RepoPath)):
		fmt.Fprintf(b, "\n  reload        automatic (run command: `%s`). Your code changes apply without a restart.\n", runCmd)
	case len(svc.Manifest.Runtime.Watch) > 0:
		b.WriteString("\n  reload        automatic, because runtime.watch is set. Your code changes apply without a restart.\n")
	default:
		fmt.Fprintf(b, "\n  reload        MANUAL (run command: `%s`). After you change the code, it runs the old code.\n", runCmd)
		fmt.Fprintf(b, "                To load your changes, run: devstack service restart %s\n", target)
		fmt.Fprintf(b, "                If the table above shows that copy as stopped, disabled or down, restart does not\n")
		fmt.Fprintf(b, "                apply. Start it: devstack service start %s\n", target)
	}
	b.WriteString("                If you change the configuration or an environment variable, you must restart the service.\n")
}

// writePrimeInstances is the one table that answers the three questions an agent
// has about the service in front of it: where is it running, on which port, and
// what is that copy for. Base and every stack are the same kind of thing — an
// instance — so splitting them across two blocks made the reader join them up,
// and left base's own port stated nowhere at all.
func writePrimeInstances(b *strings.Builder, ws *workspace.Workspace, rw *config.ResolvedWorkspace, service, here string, working *workingStack) {
	view, err := tilt.NewClient("localhost", workspace.HostTiltPort).GetView()
	if err != nil {
		b.WriteString("\nThe daemon is not started. To start it, run: `devstack workspace up`\n")
		return
	}

	states := map[string]string{}
	total := 0
	for _, r := range view.UiResources {
		name := r.Metadata.Name
		if !strings.HasPrefix(name, ws.Name+":") {
			continue
		}
		st := serviceStatus(r)
		if st == "running" {
			total++
		}
		states[strings.TrimPrefix(name, ws.Name+":")] = st
	}
	if service == "" {
		return
	}

	type instance struct{ name, port, state, branch, dir, note string }

	rows := []instance{{name: "base", port: "-", state: orDash(states[service])}}
	if svc, ok := rw.Services[service]; ok {
		rows[0].dir = svc.RepoPath
		if svc.Manifest != nil {
			if p, ok := svc.Manifest.Ports["http"]; ok {
				rows[0].port = fmt.Sprintf(":%d", p)
			}
		}
	}

	recs, _ := stack.LoadStore(ws.Name)
	sort.Slice(recs, func(i, j int) bool { return recs[i].Name < recs[j].Name })
	for _, rec := range recs {
		if !containsString(rec.Overlay, service) {
			continue
		}
		row := instance{name: rec.Name, port: "-", state: "down", note: firstLine(rec.Note, 74)}
		if p, ok := rec.Ports[stack.QualifyPortKey(service, "http")]; ok {
			row.port = fmt.Sprintf(":%d", p)
		}
		if st, ok := states[service+":"+rec.Name]; ok {
			row.state = st
		}
		row.dir = rec.Worktrees[service]
		rows = append(rows, row)
	}

	// The branch is read from each checkout rather than taken from the stack
	// record: a service pulled into an overlay because it calls a changed one is
	// detached at HEAD, not on the branch of the stack, and telling an agent
	// otherwise sends it to commit somewhere that does not exist.
	dirs := map[string]string{}
	for _, r := range rows {
		if r.dir != "" {
			dirs[r.dir] = r.dir
		}
	}
	labels := gitinfo.ReadAll(dirs)
	for i := range rows {
		if rows[i].dir != "" {
			rows[i].branch = labels[rows[i].dir].Label()
		}
	}

	fmt.Fprintf(b, "runs as %s:\n", pluralCopy(len(rows)))
	suggested := ""
	if working != nil && working.Rec != nil && working.Rec.Name != here {
		suggested = working.Rec.Name
	}

	for _, r := range rows {
		// ▸ is a filesystem fact: the directory this command ran in. ? is a
		// guess about intent. Marking a guess with ▸ told an agent it was
		// standing somewhere it was not, and the worktree path beside it made
		// the claim look verified.
		marker := " "
		switch r.name {
		case here:
			marker = "▸"
		case suggested:
			marker = "?"
		}
		fmt.Fprintf(b, "  %s %-12s %-8s %-9s branch %s\n", marker, r.name, r.port, r.state, orDash(truncateCell(r.branch, 46)))
		if r.dir != "" {
			fmt.Fprintf(b, "      %s\n", r.dir)
		}
		if r.note != "" {
			fmt.Fprintf(b, "      %s\n", r.note)
		}
	}
	fmt.Fprintf(b, "  The marker ▸ shows the copy that you are in now: %s.\n", here)
	if suggested != "" {
		fmt.Fprintf(b, "  The marker ? shows a guess. %s is the only stack that runs %s, but you are not in it.\n  Ask the user before you work on it.\n", suggested, service)
	}
	b.WriteString("  To make a command change the copy of a stack, add `--stack <name>`. Your directory does not do this.\n")
	b.WriteString("  In the worktree of a stack, `devstack service restart <svc>` restarts the copy of base.\n")
	b.WriteString("  Some read-only commands do read your directory: `stack config` and `env which` name the stack you\n")
	b.WriteString("  are in. No command that starts, stops or writes does. To reach a copy over the network, use its port.\n")
}

// pluralCopy keeps the count grammatical. "1 copy(s)" makes a reader stop and
// parse, which is the opposite of what a briefing is for.
func pluralCopyRunning(n int) string {
	if n == 1 {
		return "1 copy runs"
	}
	return fmt.Sprintf("%d copies run", n)
}

func pluralCopy(n int) string {
	if n == 1 {
		return "1 copy"
	}
	return fmt.Sprintf("%d copies", n)
}

// section writes a heading. The briefing is injected whole into a session, so a
// reader cannot skip to the part it needs unless the parts are named. The
// headings are short because every one of them is paid for on every session.
func section(b *strings.Builder, title string) {
	fmt.Fprintf(b, "\n## %s\n", title)
}
