package hostdaemon

import (
	"reflect"
	"strings"
	"testing"
)

const twoServices = `# GENERATED BY devstack — DO NOT EDIT.
# Source of truth: devstack.workspace.yaml + each service's devstack.service.yaml.

# navexa:api
local_resource(
    "navexa:api",
    serve_cmd="dotnet run",
    serve_env={
        "PORT": "5000",
    },
)

# navexa:worker
local_resource(
    "navexa:worker",
    serve_cmd="python main.py",
)
`

func TestResourceBlocksSkipsFileHeader(t *testing.T) {
	blocks := resourceBlocks(twoServices)
	got := make([]string, 0, len(blocks))
	for name := range blocks {
		got = append(got, name)
	}
	if len(got) != 2 {
		t.Fatalf("resourceBlocks() = %v, want exactly the two service blocks", got)
	}
	for _, want := range []string{"navexa:api", "navexa:worker"} {
		if _, ok := blocks[want]; !ok {
			t.Errorf("resourceBlocks() missing %q; got %v", want, got)
		}
	}
}

func TestChangedResourcesIdenticalRenderings(t *testing.T) {
	if got := changedResources(twoServices, twoServices); len(got) != 0 {
		t.Errorf("changedResources(x, x) = %v, want none", got)
	}
}

func TestChangedResourcesNamesOnlyTheEditedService(t *testing.T) {
	edited := strings.Replace(twoServices, `"PORT": "5000"`, `"PORT": "5001"`, 1)
	got := changedResources(twoServices, edited)
	if want := []string{"navexa:api"}; !reflect.DeepEqual(got, want) {
		t.Errorf("changedResources() = %v, want %v", got, want)
	}
}

func TestChangedResourcesReportsAddedAndRemoved(t *testing.T) {
	added := twoServices + "\n# navexa:cache\nlocal_resource(\n    \"navexa:cache\",\n)\n"
	if got, want := changedResources(twoServices, added), []string{"navexa:cache"}; !reflect.DeepEqual(got, want) {
		t.Errorf("added: changedResources() = %v, want %v", got, want)
	}
	if got, want := changedResources(added, twoServices), []string{"navexa:cache"}; !reflect.DeepEqual(got, want) {
		t.Errorf("removed: changedResources() = %v, want %v", got, want)
	}
}

// changedResources must survive a first run where no Tiltfile existed yet.
func TestChangedResourcesFromEmpty(t *testing.T) {
	got := changedResources("", twoServices)
	want := []string{"navexa:api", "navexa:worker"}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("changedResources(\"\", x) = %v, want %v", got, want)
	}
}
